In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [3]:
lstm = nn.LSTM(3, 3)

In [4]:
lstm.half

<bound method Module.half of LSTM(3, 3)>

In [4]:
inputs = [torch.randn(1, 3) for _ in range(5)]

In [5]:
x = torch.randn(64, 70, 300)

In [9]:
x.shape

torch.Size([64, 70, 300])

In [19]:
len(x.unbind(2))

300

In [5]:
inputs

[tensor([[-0.5525,  0.6355, -0.3968]]),
 tensor([[-0.6571, -1.6428,  0.9803]]),
 tensor([[-0.0421, -0.8206,  0.3133]]),
 tensor([[-1.1352,  0.3773, -0.2824]]),
 tensor([[-2.5667, -1.4303,  0.5009]])]

In [20]:
torch.unbind(torch.tensor([[1, 2, 3],
                                [4, 5, 6],
                               [7, 8, 9]]))

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

In [6]:
hidden = (torch.randn(1, 1, 3),
          torch.randn(1, 1, 3))

In [7]:
hidden

(tensor([[[ 0.5438, -0.4057,  1.1341]]]),
 tensor([[[-1.1115,  0.3501, -0.7703]]]))

In [8]:
i = inputs[0].view(1,1,-1)
i.shape

torch.Size([1, 1, 3])

In [9]:
lstm(i,hidden)

(tensor([[[-0.2682,  0.0304, -0.1526]]], grad_fn=<StackBackward>),
 (tensor([[[-0.2682,  0.0304, -0.1526]]], grad_fn=<StackBackward>),
  tensor([[[-1.0766,  0.0972, -0.5498]]], grad_fn=<StackBackward>)))

In [10]:
inputs = torch.cat(inputs).view(len(inputs), 1, -1)
hidden = (torch.randn(1, 1, 3), torch.randn(1, 1, 3))

In [11]:
inputs

tensor([[[-0.5525,  0.6355, -0.3968]],

        [[-0.6571, -1.6428,  0.9803]],

        [[-0.0421, -0.8206,  0.3133]],

        [[-1.1352,  0.3773, -0.2824]],

        [[-2.5667, -1.4303,  0.5009]]])

In [12]:
out,hidden = lstm(inputs,hidden)

In [13]:
out

tensor([[[-0.0187,  0.1713, -0.2944]],

        [[-0.3521,  0.1026, -0.2971]],

        [[-0.3191,  0.0781, -0.1957]],

        [[-0.1634,  0.0941, -0.1637]],

        [[-0.3368,  0.0959, -0.0538]]], grad_fn=<StackBackward>)

In [14]:
hidden

(tensor([[[-0.3368,  0.0959, -0.0538]]], grad_fn=<StackBackward>),
 tensor([[[-0.9825,  0.4715, -0.0633]]], grad_fn=<StackBackward>))

In [15]:
c=torch.rand(3,4,5)

In [16]:
c

tensor([[[0.4422, 0.4828, 0.0281, 0.1782, 0.2079],
         [0.2861, 0.8555, 0.3366, 0.1264, 0.6924],
         [0.6601, 0.8238, 0.2413, 0.6084, 0.3180],
         [0.3877, 0.1015, 0.2721, 0.3469, 0.7138]],

        [[0.5913, 0.6235, 0.9991, 0.9873, 0.8410],
         [0.5159, 0.1541, 0.8908, 0.3750, 0.4596],
         [0.0693, 0.4012, 0.1775, 0.9595, 0.0677],
         [0.1103, 0.4830, 0.2296, 0.6789, 0.3075]],

        [[0.2652, 0.5283, 0.8619, 0.1483, 0.7348],
         [0.8212, 0.9891, 0.1500, 0.6211, 0.1303],
         [0.9269, 0.3060, 0.8012, 0.5149, 0.4611],
         [0.4840, 0.5850, 0.7357, 0.5802, 0.6525]]])

In [17]:
c.permute(0,2,1).shape

torch.Size([3, 5, 4])

In [9]:
c.permute(1,0,2).shape

torch.Size([4, 3, 5])

In [7]:
c[1].T,c.shape

(tensor([[0.3138, 0.5239, 0.6397, 0.2588],
         [0.1980, 0.7981, 0.9743, 0.9391],
         [0.4162, 0.7718, 0.8300, 0.4167],
         [0.2843, 0.0112, 0.0444, 0.7140],
         [0.3398, 0.8100, 0.0246, 0.2676]]), torch.Size([3, 4, 5]))

In [13]:
#permute is basically transpose of each rank of a tensor

In [19]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [12]:
t.reshape([1,12])

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [13]:
t.reshape([1,12]).squeeze().unsqueeze(dim=0).shape

torch.Size([1, 12])

In [14]:
t.reshape([1,12]).squeeze().unsqueeze(dim=1).shape

torch.Size([12, 1])

In [20]:
try:
    
    t.reshape([1,12]).squeeze().unsqueeze(dim=2).shape
except IndexError as e:
    print(str(e))
    print("Can't unsqueeze at dim greater than rank")

Dimension out of range (expected to be in range of [-2, 1], but got 2)
Can't unsqueeze at dim greater than rank


In [18]:
def flatten(t):
    if len(t.shape) > 1:
        
        t = t.reshape(1, -1)
        t = t.squeeze()
    return t

In [19]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [20]:
flatten(c)

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999, 0.3971, 0.7544, 0.5695,
        0.4388, 0.6387, 0.5247, 0.6826, 0.3051, 0.4635, 0.4550, 0.5725, 0.4980,
        0.9371, 0.6556, 0.3138, 0.1980, 0.4162, 0.2843, 0.3398, 0.5239, 0.7981,
        0.7718, 0.0112, 0.8100, 0.6397, 0.9743, 0.8300, 0.0444, 0.0246, 0.2588,
        0.9391, 0.4167, 0.7140, 0.2676, 0.9906, 0.2885, 0.8750, 0.5059, 0.2366,
        0.7570, 0.2346, 0.6471, 0.3556, 0.4452, 0.0193, 0.2616, 0.7713, 0.3785,
        0.9980, 0.9008, 0.4766, 0.1663, 0.8045, 0.6552])

In [22]:
flatten(torch.ones(4))

tensor([1., 1., 1., 1.])

In [23]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])

In [24]:
t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [25]:
t1.shape,t2.shape

(torch.Size([2, 2]), torch.Size([2, 2]))

In [29]:
torch.cat((t1, t2), dim=0),torch.cat((t1, t2), dim=0).shape

(tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]), torch.Size([4, 2]))

In [2]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

In [3]:
t1.shape

torch.Size([4, 4])

In [8]:
t0 = torch.stack((t1, t2, t3),dim=1)

In [11]:
t0,t0.shape

(tensor([[[1, 1, 1, 1],
          [2, 2, 2, 2],
          [3, 3, 3, 3]],
 
         [[1, 1, 1, 1],
          [2, 2, 2, 2],
          [3, 3, 3, 3]],
 
         [[1, 1, 1, 1],
          [2, 2, 2, 2],
          [3, 3, 3, 3]],
 
         [[1, 1, 1, 1],
          [2, 2, 2, 2],
          [3, 3, 3, 3]]]), torch.Size([4, 3, 4]))

In [45]:
t0 = t0.reshape(3,1,4,4)

In [47]:
t0[0].shape

torch.Size([1, 4, 4])

In [48]:
flatten(t0)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [49]:
t0.flatten(start_dim=1).shape

torch.Size([3, 16])

In [51]:
t0.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [52]:
r = torch.ones(1,2,2)
g = torch.ones(1,2,2) + 1
b = torch.ones(1,2,2) + 2

In [55]:
img = torch.cat(
    (r,g,b)
    ,dim=0
)

In [67]:
img_stack = torch.stack((r,g,b))

In [71]:
img_stack.shape,img_stack

(torch.Size([3, 1, 2, 2]), tensor([[[[1., 1.],
           [1., 1.]]],
 
 
         [[[2., 2.],
           [2., 2.]]],
 
 
         [[[3., 3.],
           [3., 3.]]]]))

tensor([[1., 1.],
        [1., 1.]])

In [70]:
img.shape

torch.Size([3, 2, 2])

In [72]:
img

tensor([[[1., 1.],
         [1., 1.]],

        [[2., 2.],
         [2., 2.]],

        [[3., 3.],
         [3., 3.]]])

In [58]:
img.flatten(start_dim=1)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

### Difference between stack and concat

In [75]:
t1 = torch.tensor([1,1,1])
t2 = torch.tensor([2,2,2])
t3 = torch.tensor([3,3,3])

In [76]:
t1.shape,t2.shape,t3.shape

(torch.Size([3]), torch.Size([3]), torch.Size([3]))

In [79]:
torch.stack(
    (t1,t2,t3)
    ,dim=0
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [83]:
t1[:,None]

tensor([[1],
        [1],
        [1]])

In [85]:
torch.cat(
    (t1[:,None],t2[:,None],t3[:,None])
    ,1
)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [12]:
torch.cat((t1,t2,t3),dim=1).shape

torch.Size([4, 12])